# Generated by Django 5.0.6 on 2024-09-21 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_task_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Project',
            new_name='project',
        ),
    ]
